// Copyright (c) 2026 The NORA Authors
// SPDX-License-Identifier: MIT

//! Debian registry — hosted flat APT repositories with server-generated indexes.
//!
//! Implements:
//!   PUT    /deb/{repo}/{*path}  — upload a .deb (parses control, regenerates indexes)
//!   GET    /deb/{repo}/{*path}  — download a package or index file
//!   HEAD   /deb/{repo}/{*path}  — existence/size check
//!   DELETE /deb/{repo}/{*path}  — remove a package (regenerates indexes)
//!
//! Each `{repo}` is an independent *flat* repository (`deb [trusted=yes]
//! {base}/deb/{repo} ./`): `Packages`, `Packages.gz`, and `Release` at the repo
//! root are regenerated on every publish/delete from per-package control
//! sidecars (parsed once at upload, same shape as the rpm handler), so a
//! rebuild never re-reads .deb payloads. Indexes are unsigned — clients use
//! `[trusted=yes]` (no InRelease/Release.gpg; GPG signing is a separate
//! roadmap item, #128).

use crate::activity_log::{ActionType, ActivityEntry};
use crate::audit::AuditEntry;
use crate::auth::{enforce_namespace_scope, NamespaceAuthority};
use crate::registry::method_not_allowed;
use crate::validation::validate_storage_key;
use crate::AppState;
use axum::{
    body::Bytes,
    extract::{Path, State},
    http::{header, StatusCode},
    response::{IntoResponse, Response},
    routing::get,
    Extension, Router,
};
use flate2::write::GzEncoder;
use serde::{Deserialize, Serialize};
use sha2::Digest;
use std::io::{Read, Write};

/// Dashboard index: group stored .deb files by repository name.
pub const INDEX_PATTERN: (&str, &str) = ("deb/", ".deb");

pub fn routes() -> Router<AppState> {
    Router::new().route(
        "/deb/{repo}/{*path}",
        get(download)
            .head(check_exists)
            .put(upload)
            .delete(delete_package)
            .fallback(|| async { method_not_allowed("GET, HEAD, PUT, DELETE") }),
    )
}

/// Sidecar prefix inside a repo. Rejected as an upload path component, so it
/// can never collide with package files.
const META_DIR: &str = ".nora-meta";
/// Index files regenerated by the server at the repo root.
const RESERVED: &[&str] = &[
    "Packages",
    "Packages.gz",
    "Release",
    "InRelease",
    "Release.gpg",
];
/// Decompressed control.tar cap — control archives are a few KB; anything
/// larger is a decompression bomb, not a package (trust boundary).
const CONTROL_TAR_MAX: u64 = 8 * 1024 * 1024;

fn package_key(repo: &str, path: &str) -> String {
    format!("deb/{repo}/{path}")
}

fn sidecar_key(repo: &str, path: &str) -> String {
    format!("deb/{repo}/{META_DIR}/{path}.json")
}

fn release_key(repo: &str) -> String {
    format!("deb/{repo}/Release")
}

/// apt resolves a flat-repo sources line (`deb <url>/deb/{repo} ./`) to
/// literal `/deb/{repo}/./InRelease` etc. — strip that leading `./` on the
/// read paths. Only the prefix apt produces; traversal stays rejected.
fn strip_flat_prefix(path: &str) -> &str {
    path.strip_prefix("./").unwrap_or(path)
}

/// Validate the `{repo}` segment and the tail path of a package operation.
/// The storage-key wrapper re-validates centrally; this is edge defence with
/// format-specific rules (single-segment repo, `.deb` suffix, reserved names).
fn validate_package_path(repo: &str, path: &str) -> Result<(), &'static str> {
    if repo.is_empty() || !repo.is_ascii() || repo.contains('/') || repo.starts_with('.') {
        return Err("Invalid repository name");
    }
    if !path.is_ascii() || path.contains("..") || path.contains('\0') || path.starts_with('/') {
        return Err("Invalid path");
    }
    if !path.to_ascii_lowercase().ends_with(".deb") {
        return Err("Only .deb files can be published");
    }
    if path
        .split('/')
        .any(|seg| seg.is_empty() || seg.starts_with('.'))
    {
        return Err("Invalid path");
    }
    if RESERVED.contains(&path) {
        return Err("Reserved index path");
    }
    Ok(())
}

// ============================================================================
// .deb parsing (ar → control.tar.{,gz,xz,zst} → control paragraph)
// ============================================================================

/// A `Write` sink with a hard cap — turns a decompression bomb into an error
/// instead of unbounded memory growth.
struct CappedVec {
    buf: Vec<u8>,
    cap: u64,
}

impl Write for CappedVec {
    fn write(&mut self, data: &[u8]) -> std::io::Result<usize> {
        if self.buf.len() as u64 + data.len() as u64 > self.cap {
            return Err(std::io::Error::other("decompressed size limit exceeded"));
        }
        self.buf.extend_from_slice(data);
        Ok(data.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn read_capped(mut reader: impl Read, cap: u64) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    reader
        .by_ref()
        .take(cap + 1)
        .read_to_end(&mut out)
        .map_err(|e| e.to_string())?;
    if out.len() as u64 > cap {
        return Err("decompressed size limit exceeded".into());
    }
    Ok(out)
}

/// Extract the `control` paragraph from a .deb archive.
fn extract_control(body: &[u8]) -> Result<String, String> {
    let mut archive = ar::Archive::new(body);
    let mut saw_debian_binary = false;
    let mut control_tar: Option<Vec<u8>> = None;
    let mut control_kind = "";

    while let Some(entry) = archive.next_entry() {
        let mut entry = entry.map_err(|e| format!("not an ar archive: {e}"))?;
        let name = String::from_utf8_lossy(entry.header().identifier()).into_owned();
        match name.as_str() {
            "debian-binary" => {
                let mut v = String::new();
                entry
                    .take(16)
                    .read_to_string(&mut v)
                    .map_err(|e| e.to_string())?;
                if v.trim() != "2.0" {
                    return Err(format!("unsupported deb format version: {}", v.trim()));
                }
                saw_debian_binary = true;
            }
            "control.tar" | "control.tar.gz" | "control.tar.xz" | "control.tar.zst" => {
                let mut raw = Vec::new();
                entry.read_to_end(&mut raw).map_err(|e| e.to_string())?;
                control_kind = match name.as_str() {
                    "control.tar" => "",
                    "control.tar.gz" => "gz",
                    "control.tar.xz" => "xz",
                    _ => "zst",
                };
                control_tar = Some(raw);
            }
            _ => {} // data.tar.* and any padding members are irrelevant here
        }
    }

    if !saw_debian_binary {
        return Err("missing debian-binary member".into());
    }
    let raw = control_tar.ok_or("missing control.tar member")?;

    let tar_bytes = match control_kind {
        "" => raw,
        "gz" => read_capped(flate2::read::GzDecoder::new(&raw[..]), CONTROL_TAR_MAX)
            .map_err(|e| format!("control.tar.gz: {e}"))?,
        "xz" => {
            let mut out = CappedVec {
                buf: Vec::new(),
                cap: CONTROL_TAR_MAX,
            };
            lzma_rs::xz_decompress(&mut &raw[..], &mut out)
                .map_err(|e| format!("control.tar.xz: {e:?}"))?;
            out.buf
        }
        _ => {
            let dec = ruzstd::decoding::StreamingDecoder::new(&raw[..])
                .map_err(|e| format!("control.tar.zst: {e}"))?;
            read_capped(dec, CONTROL_TAR_MAX).map_err(|e| format!("control.tar.zst: {e}"))?
        }
    };

    let mut tar = tar::Archive::new(&tar_bytes[..]);
    for entry in tar.entries().map_err(|e| format!("control.tar: {e}"))? {
        let mut entry = entry.map_err(|e| format!("control.tar: {e}"))?;
        let path = entry.path().map_err(|e| e.to_string())?;
        if path.file_name().and_then(|n| n.to_str()) == Some("control")
            && path.components().count() <= 2
        {
            let mut control = String::new();
            entry
                .read_to_string(&mut control)
                .map_err(|e| format!("control file: {e}"))?;
            return Ok(control);
        }
    }
    Err("control.tar has no control file".into())
}

/// Read a field from a control paragraph (simple `Name: value` lines only —
/// the fields we validate are never multi-line).
fn control_field<'a>(control: &'a str, name: &str) -> Option<&'a str> {
    control.lines().find_map(|l| {
        let (k, v) = l.split_once(':')?;
        (k == name).then(|| v.trim())
    })
}

// ============================================================================
// Package sidecar + index generation
// ============================================================================

/// Everything the Packages index needs for one package: the verbatim control
/// paragraph plus the fields computed from the uploaded bytes.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct PkgRecord {
    package: String,
    version: String,
    arch: String,
    /// Verbatim control paragraph, trailing whitespace trimmed.
    control: String,
    /// Location relative to the repo root (= the upload path).
    filename: String,
    size: u64,
    md5: String,
    sha1: String,
    sha256: String,
}

impl PkgRecord {
    /// Render the Packages-file paragraph: control fields verbatim, then the
    /// repository-computed fields (dpkg ignores field order).
    fn paragraph(&self) -> String {
        format!(
            "{}\nFilename: {}\nSize: {}\nMD5sum: {}\nSHA1: {}\nSHA256: {}\n",
            self.control.trim_end(),
            self.filename,
            self.size,
            self.md5,
            self.sha1,
            self.sha256
        )
    }
}

/// Fields the repository computes itself and appends to each paragraph — an
/// uploaded control carrying its own copy would produce duplicate (and
/// contradictory) fields in the Packages index.
const COMPUTED_FIELDS: &[&str] = &["filename", "size", "md5sum", "sha1", "sha256"];

/// Validate an uploaded control paragraph before it is embedded verbatim in
/// the shared Packages index. dpkg-deb can only build well-formed controls,
/// but this endpoint accepts anything ar/tar-shaped, and one crafted control
/// corrupts the whole repo's index: an embedded blank line splits the
/// paragraph (forging a second stanza), a duplicated Filename/SHA256
/// contradicts the computed one, and C0 bytes trip apt's parser.
fn validate_control(control: &str) -> Result<(), String> {
    for (i, line) in control.trim_end().lines().enumerate() {
        if line.trim().is_empty() {
            return Err("control contains a blank line (paragraph injection)".into());
        }
        if line.chars().any(|c| c.is_ascii_control() && c != '\t') {
            return Err("control contains a control character".into());
        }
        if line.starts_with(' ') || line.starts_with('\t') {
            if i == 0 {
                return Err("control starts with a continuation line".into());
            }
            continue;
        }
        let Some((field, _)) = line.split_once(':') else {
            return Err(format!(
                "control line {} is not a field or continuation",
                i + 1
            ));
        };
        if field.is_empty() || !field.chars().all(|c| c.is_ascii_graphic() && c != ':') {
            return Err(format!("control line {} has an invalid field name", i + 1));
        }
        if COMPUTED_FIELDS.contains(&field.to_ascii_lowercase().as_str()) {
            return Err(format!(
                "control must not carry repository-computed field {field}"
            ));
        }
    }
    Ok(())
}

fn extract_record(body: &[u8], path: &str) -> Result<PkgRecord, String> {
    let control = extract_control(body)?;
    validate_control(&control)?;
    let package = control_field(&control, "Package")
        .filter(|v| !v.is_empty())
        .ok_or("control missing Package field")?;
    let version = control_field(&control, "Version")
        .filter(|v| !v.is_empty())
        .ok_or("control missing Version field")?;
    let arch = control_field(&control, "Architecture")
        .filter(|v| !v.is_empty())
        .ok_or("control missing Architecture field")?;
    Ok(PkgRecord {
        package: package.to_string(),
        version: version.to_string(),
        arch: arch.to_string(),
        control: control.trim_end().to_string(),
        filename: path.to_string(),
        size: body.len() as u64,
        md5: hex::encode(md5::Md5::digest(body)),
        sha1: hex::encode(sha1::Sha1::digest(body)),
        sha256: hex::encode(sha2::Sha256::digest(body)),
    })
}

/// RFC 1123 date as apt expects in Release (`Thu, 10 Jul 2026 12:00:00 UTC`).
fn release_date() -> String {
    chrono::Utc::now()
        .format("%a, %d %b %Y %H:%M:%S UTC")
        .to_string()
}

fn generate_release(packages: &[u8], packages_gz: &[u8], repo: &str) -> String {
    let entry = |data: &[u8], name: &str, hasher: fn(&[u8]) -> String| {
        format!(" {} {} {}\n", hasher(data), data.len(), name)
    };
    let md5 = |d: &[u8]| hex::encode(md5::Md5::digest(d));
    let sha256 = |d: &[u8]| hex::encode(sha2::Sha256::digest(d));
    format!(
        "Origin: NORA\nLabel: {repo}\nDate: {}\nMD5Sum:\n{}{}SHA256:\n{}{}",
        release_date(),
        entry(packages, "Packages", md5),
        entry(packages_gz, "Packages.gz", md5),
        entry(packages, "Packages", sha256),
        entry(packages_gz, "Packages.gz", sha256),
    )
}

/// Rebuild Packages/Packages.gz/Release for `repo` from control sidecars.
/// Caller must hold the repo's publish lock. Fail-closed: any error aborts the
/// rebuild (and the surrounding publish) rather than writing a truncated
/// index — same contract as the cargo index and the rpm handler.
///
/// Indexes have fixed names (flat apt repos have no by-hash), so a client that
/// fetched Release mid-regeneration can see a hash mismatch on Packages; apt
/// reports it and succeeds on retry — same window as reprepro/aptly.
async fn regenerate_indexes(state: &AppState, repo: &str) -> Result<(), String> {
    let meta_prefix = format!("deb/{repo}/{META_DIR}/");
    let keys = state
        .storage
        .list(&meta_prefix)
        .await
        .map_err(|e| format!("list sidecars: {e}"))?;

    let mut pkgs = Vec::with_capacity(keys.len());
    for key in &keys {
        let data = state
            .storage
            .get(key)
            .await
            .map_err(|e| format!("read sidecar {key}: {e}"))?;
        let rec: PkgRecord =
            serde_json::from_slice(&data).map_err(|e| format!("parse sidecar {key}: {e}"))?;
        pkgs.push(rec);
    }
    // Deterministic output: same package set → byte-identical indexes
    // (modulo the Release Date field).
    pkgs.sort_by(|a, b| {
        (&a.package, &a.version, &a.filename).cmp(&(&b.package, &b.version, &b.filename))
    });

    let packages: Vec<u8> = pkgs
        .iter()
        .map(|p| p.paragraph())
        .collect::<Vec<_>>()
        .join("\n")
        .into_bytes();

    let mut enc = GzEncoder::new(Vec::new(), flate2::Compression::default());
    let packages_gz = enc
        .write_all(&packages)
        .and_then(|_| enc.finish())
        .map_err(|e| format!("gzip Packages: {e}"))?;
    let release = generate_release(&packages, &packages_gz, repo);

    // Packages before Release — Release carries their hashes, so a reader
    // never sees a Release referencing index bytes that are not there yet.
    // Signatures last, for the same reason. Fail-closed like the rest of
    // the rebuild: a repo that claims to be signed must never publish an
    // unsigned or stale-signed index (#128).
    let mut files: Vec<(&str, Vec<u8>)> = vec![
        ("Packages", packages),
        ("Packages.gz", packages_gz),
        ("Release", release.clone().into_bytes()),
    ];
    match &state.signer {
        Some(signer) => {
            files.push(("InRelease", signer.clearsign(&release)?.into_bytes()));
            files.push((
                "Release.gpg",
                signer.sign_detached(release.as_bytes())?.into_bytes(),
            ));
        }
        None => {
            // Signing turned off after having been on: stale signatures that
            // no longer match Release would hard-fail apt's verification.
            for name in ["InRelease", "Release.gpg"] {
                let key = format!("deb/{repo}/{name}");
                if state.storage.stat(&key).await.is_some() {
                    state
                        .storage
                        .delete(&key)
                        .await
                        .map_err(|e| format!("delete stale {name}: {e}"))?;
                }
            }
        }
    }
    for (name, data) in files {
        state
            .storage
            .put(&format!("deb/{repo}/{name}"), &data)
            .await
            .map_err(|e| format!("write {name}: {e}"))?;
    }
    Ok(())
}

// ============================================================================
// Handlers
// ============================================================================

async fn upload(
    State(state): State<AppState>,
    Path((repo, path)): Path<(String, String)>,
    Extension(authority): Extension<NamespaceAuthority>,
    body: Bytes,
) -> Response {
    if !state.config.deb.enabled {
        return StatusCode::NOT_FOUND.into_response();
    }
    if let Err(msg) = validate_package_path(&repo, &path) {
        return (StatusCode::BAD_REQUEST, msg).into_response();
    }
    // Enforce OIDC namespace_scope on the repository name (#583).
    if enforce_namespace_scope(&authority, &repo).is_err() {
        return StatusCode::FORBIDDEN.into_response();
    }
    if body.len() as u64 > state.config.deb.max_file_size {
        return (
            StatusCode::PAYLOAD_TOO_LARGE,
            format!(
                "File too large. Max size: {} bytes",
                state.config.deb.max_file_size
            ),
        )
            .into_response();
    }

    let record = match extract_record(&body, &path) {
        Ok(r) => r,
        Err(e) => {
            return (StatusCode::BAD_REQUEST, format!("Not a valid deb: {e}")).into_response()
        }
    };
    let sidecar = match serde_json::to_vec(&record) {
        Ok(j) => j,
        Err(e) => {
            tracing::error!(error = %e, "deb: failed to serialize package record");
            return StatusCode::INTERNAL_SERVER_ERROR.into_response();
        }
    };

    let key = package_key(&repo, &path);
    if validate_storage_key(&key).is_err() {
        return StatusCode::BAD_REQUEST.into_response();
    }

    // Serialize publishes/deletes per repo: the index rebuild is a
    // list-read-generate-write cycle over the whole repo (same TOCTOU
    // rationale as the maven-metadata.xml lock).
    let lock = state.publish_lock(&release_key(&repo));
    let _guard = lock.lock().await;

    if let Err(e) = state.storage.put(&key, &body).await {
        tracing::error!(error = %e, key = %key, "deb: failed to store package");
        return StatusCode::INTERNAL_SERVER_ERROR.into_response();
    }
    if let Err(e) = state
        .storage
        .put(&sidecar_key(&repo, &path), &sidecar)
        .await
    {
        tracing::error!(error = %e, key = %key, "deb: failed to store metadata sidecar");
        return StatusCode::INTERNAL_SERVER_ERROR.into_response();
    }
    if let Err(e) = regenerate_indexes(&state, &repo).await {
        tracing::error!(repo = %repo, error = %e, "deb: index regeneration failed");
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            "Package stored but index regeneration failed",
        )
            .into_response();
    }

    let nva = format!("{}_{}_{}", record.package, record.version, record.arch);
    state.metrics.record_upload("deb");
    state
        .audit
        .log(AuditEntry::new("push", "api", &nva, "deb", ""));
    state.activity.push(ActivityEntry::new(
        ActionType::Push,
        format!("{repo}/{nva}"),
        crate::registry_type::RegistryType::Deb,
        "LOCAL",
    ));
    state.repo_index.invalidate("deb");

    StatusCode::CREATED.into_response()
}

async fn download(
    State(state): State<AppState>,
    Path((repo, path)): Path<(String, String)>,
) -> Response {
    if !state.config.deb.enabled {
        return StatusCode::NOT_FOUND.into_response();
    }
    let path = strip_flat_prefix(&path).to_string();
    if path == "pubkey.gpg" {
        return match &state.signer {
            Some(signer) => (
                StatusCode::OK,
                [(header::CONTENT_TYPE, "application/pgp-keys")],
                signer.public_key_armored().to_string(),
            )
                .into_response(),
            None => StatusCode::NOT_FOUND.into_response(),
        };
    }
    let key = package_key(&repo, &path);
    if validate_storage_key(&key).is_err() || path.starts_with(META_DIR) {
        return StatusCode::BAD_REQUEST.into_response();
    }

    match state.storage.get_verified(&key).await {
        Ok(outcome) => {
            state.metrics.record_download("deb");
            state.activity.push(ActivityEntry::new(
                ActionType::Pull,
                format!("{repo}/{path}"),
                crate::registry_type::RegistryType::Deb,
                "LOCAL",
            ));
            use nora_registry::verified::{verified_body, GateOutcome};
            let data = match outcome {
                GateOutcome::Verified(blob) => verified_body(blob),
                GateOutcome::Unpinned(blob) => blob.into_inner(),
            };
            let mut builder = axum::http::Response::builder()
                .status(StatusCode::OK)
                .header(header::CONTENT_TYPE, content_type(&path));
            // Index files are rewritten in place on every publish (fixed
            // names, no by-hash in flat repos) — clients must revalidate.
            if RESERVED.contains(&path.as_str()) {
                builder = builder.header(header::CACHE_CONTROL, "no-cache");
            }
            builder
                .body(axum::body::Body::from(data))
                .expect("valid response")
                .into_response()
        }
        Err(crate::storage::StorageError::NotFound) => StatusCode::NOT_FOUND.into_response(),
        Err(e) => {
            tracing::error!(error = %e, key = %key, "deb: failed to read artifact");
            StatusCode::INTERNAL_SERVER_ERROR.into_response()
        }
    }
}

async fn check_exists(
    State(state): State<AppState>,
    Path((repo, path)): Path<(String, String)>,
) -> Response {
    if !state.config.deb.enabled {
        return StatusCode::NOT_FOUND.into_response();
    }
    let path = strip_flat_prefix(&path).to_string();
    let key = package_key(&repo, &path);
    if validate_storage_key(&key).is_err() || path.starts_with(META_DIR) {
        return StatusCode::BAD_REQUEST.into_response();
    }
    match state.storage.stat(&key).await {
        Some(meta) => (
            StatusCode::OK,
            [
                (header::CONTENT_LENGTH, meta.size.to_string()),
                (header::CONTENT_TYPE, content_type(&path).to_string()),
            ],
        )
            .into_response(),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

async fn delete_package(
    State(state): State<AppState>,
    Path((repo, path)): Path<(String, String)>,
    Extension(authority): Extension<NamespaceAuthority>,
) -> Response {
    if !state.config.deb.enabled {
        return StatusCode::NOT_FOUND.into_response();
    }
    if let Err(msg) = validate_package_path(&repo, &path) {
        return (StatusCode::BAD_REQUEST, msg).into_response();
    }
    if enforce_namespace_scope(&authority, &repo).is_err() {
        return StatusCode::FORBIDDEN.into_response();
    }
    let key = package_key(&repo, &path);
    if validate_storage_key(&key).is_err() {
        return StatusCode::BAD_REQUEST.into_response();
    }

    let lock = state.publish_lock(&release_key(&repo));
    let _guard = lock.lock().await;

    match state.storage.delete(&key).await {
        Ok(()) => {}
        Err(crate::storage::StorageError::NotFound) => {
            return StatusCode::NOT_FOUND.into_response()
        }
        Err(e) => {
            tracing::error!(error = %e, key = %key, "deb: failed to delete package");
            return StatusCode::INTERNAL_SERVER_ERROR.into_response();
        }
    }
    if let Err(e) = state.storage.delete(&sidecar_key(&repo, &path)).await {
        tracing::warn!(error = %e, key = %key, "deb: failed to delete metadata sidecar");
    }
    if let Err(e) = regenerate_indexes(&state, &repo).await {
        tracing::error!(repo = %repo, error = %e, "deb: index regeneration failed");
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            "Package deleted but index regeneration failed",
        )
            .into_response();
    }

    state
        .audit
        .log(AuditEntry::new("delete", "api", &path, "deb", ""));
    state.repo_index.invalidate("deb");
    StatusCode::NO_CONTENT.into_response()
}

fn content_type(path: &str) -> &'static str {
    if path.ends_with(".deb") {
        "application/vnd.debian.binary-package"
    } else if path.ends_with(".gz") {
        "application/gzip"
    } else {
        "text/plain; charset=utf-8"
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_package_path() {
        assert!(validate_package_path("myrepo", "pool/tree_2.1.0_amd64.deb").is_ok());
        assert!(validate_package_path("myrepo", "tree.deb").is_ok());
        assert!(validate_package_path("a/b", "x.deb").is_err()); // multi-segment repo
        assert!(validate_package_path("", "x.deb").is_err());
        assert!(validate_package_path(".hidden", "x.deb").is_err());
        assert!(validate_package_path("myrepo", "Packages").is_err()); // not .deb
        assert!(validate_package_path("myrepo", ".nora-meta/x.deb").is_err()); // dot segment
        assert!(validate_package_path("myrepo", "a/../b.deb").is_err()); // traversal
        assert!(validate_package_path("myrepo", "/abs.deb").is_err());
    }

    #[test]
    fn test_control_field() {
        let c = "Package: tree\nVersion: 2.1.0-1\nArchitecture: amd64\n";
        assert_eq!(control_field(c, "Package"), Some("tree"));
        assert_eq!(control_field(c, "Version"), Some("2.1.0-1"));
        assert_eq!(control_field(c, "Missing"), None);
    }

    #[test]
    fn test_paragraph_appends_computed_fields() {
        let rec = PkgRecord {
            package: "tree".into(),
            version: "2.1.0-1".into(),
            arch: "amd64".into(),
            control: "Package: tree\nVersion: 2.1.0-1\nArchitecture: amd64".into(),
            filename: "pool/tree.deb".into(),
            size: 42,
            md5: "m".into(),
            sha1: "s1".into(),
            sha256: "s256".into(),
        };
        let p = rec.paragraph();
        assert!(p.contains("Package: tree\n"));
        assert!(p.contains("Filename: pool/tree.deb\n"));
        assert!(p.contains("Size: 42\n"));
        assert!(p.contains("SHA256: s256\n"));
        assert!(p.ends_with('\n') && !p.ends_with("\n\n"));
    }

    #[test]
    fn test_extract_control_all_compressions() {
        for comp in ["", "gz", "xz", "zst"] {
            let deb = super::integration_tests::build_test_deb_with("tree", "1.0-1", comp);
            let control = extract_control(&deb).unwrap_or_else(|e| panic!("{comp}: {e}"));
            assert_eq!(control_field(&control, "Package"), Some("tree"), "{comp}");
        }
    }

    #[test]
    fn test_validate_control() {
        let ok = "Package: tree\nVersion: 1.0-1\nArchitecture: amd64\nDescription: x\n multi-line continuation\n";
        assert!(validate_control(ok).is_ok());
        // Trailing newline alone is not a blank line.
        assert!(validate_control("Package: a\n").is_ok());

        // Paragraph injection: a blank line would split the Packages stanza.
        assert!(validate_control("Package: a\n\nPackage: bash\nEvil: 1").is_err());
        assert!(validate_control("Package: a\n \nX: y").is_err()); // whitespace-only line
                                                                   // Repository-computed fields must not be uploader-supplied.
        for f in [
            "Filename: ../x.deb",
            "SHA256: 00",
            "Size: 1",
            "MD5sum: 0",
            "sha1: 0",
        ] {
            assert!(
                validate_control(&format!("Package: a\n{f}")).is_err(),
                "{f}"
            );
        }
        // C0 controls (incl. NUL and CR — valid UTF-8, hostile to apt's parser).
        assert!(validate_control("Package: a\u{0}b").is_err());
        assert!(validate_control("Package: a\rb").is_err());
        assert!(validate_control("Package: a\u{01}b").is_err());
        // Structure: first-line continuation, non-field line, bad field name.
        assert!(validate_control(" leading continuation").is_err());
        assert!(validate_control("Package: a\nnot a field line").is_err());
        assert!(validate_control("Bad Field: x").is_err());
        // Tabs in values are fine (legal in deb822).
        assert!(validate_control("Package: a\nX: a\tb").is_ok());
    }

    #[test]
    fn test_extract_control_rejects_garbage_and_bombs() {
        assert!(extract_control(b"not an ar archive").is_err());

        // 32 MiB of zeros gzips to ~32 KiB — must trip the decompressed cap,
        // not allocate the plaintext.
        let mut tarb = tar::Builder::new(Vec::new());
        let mut hdr = tar::Header::new_gnu();
        hdr.set_path("./control").unwrap();
        hdr.set_size(32 * 1024 * 1024);
        hdr.set_cksum();
        tarb.append(&hdr, std::io::repeat(0).take(32 * 1024 * 1024))
            .unwrap();
        let tar_bytes = tarb.into_inner().unwrap();
        let mut enc = GzEncoder::new(Vec::new(), flate2::Compression::default());
        enc.write_all(&tar_bytes).unwrap();
        let gz = enc.finish().unwrap();

        let mut arb = ar::Builder::new(Vec::new());
        arb.append(
            &ar::Header::new(b"debian-binary".to_vec(), 4),
            &b"2.0\n"[..],
        )
        .unwrap();
        arb.append(
            &ar::Header::new(b"control.tar.gz".to_vec(), gz.len() as u64),
            &gz[..],
        )
        .unwrap();
        let deb = arb.into_inner().unwrap();

        let err = extract_control(&deb).unwrap_err();
        assert!(err.contains("size limit"), "{err}");
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod integration_tests {
    use super::RESERVED;
    use crate::test_helpers::{body_bytes, create_test_context, send};
    use axum::http::{Method, StatusCode};
    use sha2::Digest;
    use std::io::Write;

    /// Build a real .deb in memory: ar(debian-binary, control.tar.<comp>,
    /// data.tar.gz) — exercises the same parse path dpkg-built packages hit.
    pub(super) fn build_test_deb_with(name: &str, version: &str, compression: &str) -> Vec<u8> {
        let control = format!(
            "Package: {name}\nVersion: {version}\nArchitecture: amd64\nMaintainer: Test <test@example.com>\nInstalled-Size: 10\nDepends: libc6 (>= 2.34)\nSection: utils\nPriority: optional\nDescription: A test package\n built for the NORA deb registry tests\n"
        );
        build_test_deb_from_control(&control, compression)
    }

    pub(super) fn build_test_deb_from_control(control: &str, compression: &str) -> Vec<u8> {
        let mut tarb = tar::Builder::new(Vec::new());
        let mut hdr = tar::Header::new_gnu();
        hdr.set_path("./control").unwrap();
        hdr.set_size(control.len() as u64);
        hdr.set_mode(0o644);
        hdr.set_cksum();
        tarb.append(&hdr, control.as_bytes()).unwrap();
        let tar_bytes = tarb.into_inner().unwrap();

        let (member, bytes): (&str, Vec<u8>) = match compression {
            "" => ("control.tar", tar_bytes),
            "gz" => {
                let mut enc =
                    flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
                enc.write_all(&tar_bytes).unwrap();
                ("control.tar.gz", enc.finish().unwrap())
            }
            "xz" => {
                let mut out = Vec::new();
                lzma_rs::xz_compress(&mut &tar_bytes[..], &mut out).unwrap();
                ("control.tar.xz", out)
            }
            _ => (
                "control.tar.zst",
                ruzstd::encoding::compress_to_vec(
                    &tar_bytes[..],
                    ruzstd::encoding::CompressionLevel::Fastest,
                ),
            ),
        };

        let mut arb = ar::Builder::new(Vec::new());
        arb.append(
            &ar::Header::new(b"debian-binary".to_vec(), 4),
            &b"2.0\n"[..],
        )
        .unwrap();
        arb.append(
            &ar::Header::new(member.as_bytes().to_vec(), bytes.len() as u64),
            &bytes[..],
        )
        .unwrap();
        // Empty data.tar.gz — present like a real deb, ignored by the parser.
        let empty_tar = tar::Builder::new(Vec::new()).into_inner().unwrap();
        let mut enc = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        enc.write_all(&empty_tar).unwrap();
        let data_gz = enc.finish().unwrap();
        arb.append(
            &ar::Header::new(b"data.tar.gz".to_vec(), data_gz.len() as u64),
            &data_gz[..],
        )
        .unwrap();
        arb.into_inner().unwrap()
    }

    fn build_test_deb(name: &str, version: &str) -> Vec<u8> {
        build_test_deb_with(name, version, "zst")
    }

    #[tokio::test]
    async fn test_deb_upload_generates_indexes() {
        let ctx = create_test_context();
        let body = build_test_deb("tree", "2.1.0-1");

        let resp = send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/pool/tree_2.1.0-1_amd64.deb",
            body.clone(),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::CREATED);

        // Packages: verbatim control + computed fields.
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Packages", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers()
                .get("cache-control")
                .unwrap()
                .to_str()
                .unwrap(),
            "no-cache"
        );
        let packages = String::from_utf8(body_bytes(resp).await.to_vec()).unwrap();
        assert!(packages.contains("Package: tree\n"), "{packages}");
        assert!(packages.contains("Version: 2.1.0-1\n"));
        assert!(packages.contains("Depends: libc6 (>= 2.34)\n"));
        assert!(packages.contains("Filename: pool/tree_2.1.0-1_amd64.deb\n"));
        assert!(packages.contains(&format!("Size: {}\n", body.len())));
        let sha256 = hex::encode(sha2::Sha256::digest(&body));
        assert!(packages.contains(&format!("SHA256: {sha256}\n")));

        // Packages.gz decompresses to the same bytes.
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Packages.gz", "").await;
        let gz = body_bytes(resp).await;
        let mut plain = String::new();
        std::io::Read::read_to_string(&mut flate2::read::GzDecoder::new(&gz[..]), &mut plain)
            .unwrap();
        assert_eq!(plain, packages);

        // Release carries correct hashes of both index files.
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Release", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        let release = String::from_utf8(body_bytes(resp).await.to_vec()).unwrap();
        let pkg_sha = hex::encode(sha2::Sha256::digest(packages.as_bytes()));
        let gz_sha = hex::encode(sha2::Sha256::digest(&gz));
        assert!(release.contains("SHA256:\n"), "{release}");
        assert!(release.contains(&format!(" {pkg_sha} {} Packages\n", packages.len())));
        assert!(release.contains(&format!(" {gz_sha} {} Packages.gz\n", gz.len())));

        // Package downloads back byte-identical.
        let resp = send(
            &ctx.app,
            Method::GET,
            "/deb/myrepo/pool/tree_2.1.0-1_amd64.deb",
            "",
        )
        .await;
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers()
                .get("content-type")
                .unwrap()
                .to_str()
                .unwrap(),
            "application/vnd.debian.binary-package"
        );
        assert_eq!(&body_bytes(resp).await[..], &body[..]);
    }

    #[tokio::test]
    async fn test_deb_multiple_packages_sorted() {
        let ctx = create_test_context();
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/zzz.deb",
            build_test_deb("zzz", "1.0"),
        )
        .await;
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/aaa.deb",
            build_test_deb("aaa", "1.0"),
        )
        .await;

        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Packages", "").await;
        let packages = String::from_utf8(body_bytes(resp).await.to_vec()).unwrap();
        let a = packages.find("Package: aaa\n").unwrap();
        let z = packages.find("Package: zzz\n").unwrap();
        assert!(a < z, "paragraphs must be sorted by package name");
        // Paragraphs separated by exactly one blank line.
        assert!(packages.contains("\n\nPackage: zzz\n"), "{packages}");
    }

    #[tokio::test]
    async fn test_deb_delete_regenerates_empty_indexes() {
        let ctx = create_test_context();
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/tree.deb",
            build_test_deb("tree", "1.0"),
        )
        .await;

        let resp = send(&ctx.app, Method::DELETE, "/deb/myrepo/tree.deb", "").await;
        assert_eq!(resp.status(), StatusCode::NO_CONTENT);

        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/tree.deb", "").await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);

        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Packages", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        let packages = String::from_utf8(body_bytes(resp).await.to_vec()).unwrap();
        assert!(!packages.contains("Package:"), "{packages}");

        let resp = send(&ctx.app, Method::DELETE, "/deb/myrepo/tree.deb", "").await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn test_deb_upload_rejects_invalid() {
        let ctx = create_test_context();

        let resp = send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/x.deb",
            b"garbage".to_vec(),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);

        let resp = send(&ctx.app, Method::PUT, "/deb/myrepo/x.txt", b"data".to_vec()).await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);

        let keys = ctx.state.storage.list("deb/").await.unwrap();
        assert!(keys.is_empty(), "rejected uploads must not write: {keys:?}");
    }

    /// A hand-crafted .deb whose control would corrupt the shared Packages
    /// index (paragraph injection / computed-field forgery) is rejected at
    /// upload — dpkg-deb can't build these, but this endpoint accepts raw
    /// ar/tar, so the server must enforce well-formedness itself.
    #[tokio::test]
    async fn test_deb_upload_rejects_index_corrupting_control() {
        let ctx = create_test_context();
        for control in [
            // Blank line forges a second stanza claiming to be bash.
            "Package: a\nVersion: 1\nArchitecture: amd64\n\nPackage: bash\nVersion: 999\n",
            // Uploader-supplied SHA256 would contradict the computed one.
            "Package: a\nVersion: 1\nArchitecture: amd64\nSHA256: 0000\n",
            // Filename hijack.
            "Package: a\nVersion: 1\nArchitecture: amd64\nFilename: pool/other.deb\n",
        ] {
            let deb = build_test_deb_from_control(control, "gz");
            let resp = send(&ctx.app, Method::PUT, "/deb/myrepo/x.deb", deb).await;
            assert_eq!(resp.status(), StatusCode::BAD_REQUEST, "{control:?}");
        }
        assert!(ctx.state.storage.list("deb/").await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn test_deb_max_file_size_enforced() {
        let ctx =
            crate::test_helpers::create_test_context_with_config(|c| c.deb.max_file_size = 16);
        let resp = send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/big.deb",
            build_test_deb("big", "1.0"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::PAYLOAD_TOO_LARGE);
    }

    #[tokio::test]
    async fn test_deb_namespace_scope_enforced() {
        use crate::config::ScopeEnforcement;

        let ctx = create_test_context();
        let scoped = |mode| {
            crate::auth::NamespaceAuthority::from_oidc_scope("ci", &["myrepo".to_string()], mode)
        };

        let resp = super::upload(
            axum::extract::State(ctx.state.clone()),
            axum::extract::Path(("otherrepo".to_string(), "x.deb".to_string())),
            axum::Extension(scoped(ScopeEnforcement::Enforce)),
            axum::body::Bytes::from(build_test_deb("x", "1.0")),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
        assert!(ctx.state.storage.list("deb/").await.unwrap().is_empty());

        let resp = super::upload(
            axum::extract::State(ctx.state.clone()),
            axum::extract::Path(("myrepo".to_string(), "x.deb".to_string())),
            axum::Extension(scoped(ScopeEnforcement::Enforce)),
            axum::body::Bytes::from(build_test_deb("x", "1.0")),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::CREATED);

        let resp = super::delete_package(
            axum::extract::State(ctx.state.clone()),
            axum::extract::Path(("otherrepo".to_string(), "x.deb".to_string())),
            axum::Extension(scoped(ScopeEnforcement::Enforce)),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn test_deb_head_and_sidecars_not_served() {
        let ctx = create_test_context();
        let body = build_test_deb("tree", "1.0");
        let len = body.len();
        send(&ctx.app, Method::PUT, "/deb/myrepo/tree.deb", body).await;

        let resp = send(&ctx.app, Method::HEAD, "/deb/myrepo/tree.deb", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers()
                .get("content-length")
                .unwrap()
                .to_str()
                .unwrap(),
            len.to_string()
        );

        let resp = send(
            &ctx.app,
            Method::GET,
            "/deb/myrepo/.nora-meta/tree.deb.json",
            "",
        )
        .await;
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    }

    #[tokio::test]
    async fn test_deb_disabled_returns_404() {
        let ctx = crate::test_helpers::create_test_context_with_config(|c| c.deb.enabled = false);
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Release", "").await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
        let resp = send(&ctx.app, Method::PUT, "/deb/myrepo/x.deb", b"x".to_vec()).await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }

    /// apt resolves the flat-repo `./` component literally: it requests
    /// `/deb/{repo}/./Packages`. Must serve, not 400.
    #[tokio::test]
    async fn test_deb_apt_dot_slash_paths_served() {
        let ctx = create_test_context();
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/pool/tree.deb",
            build_test_deb("tree", "1.0"),
        )
        .await;
        for path in [
            "./Release",
            "./Packages",
            "./Packages.gz",
            "./pool/tree.deb",
        ] {
            let resp = send(&ctx.app, Method::GET, &format!("/deb/myrepo/{path}"), "").await;
            assert_eq!(resp.status(), StatusCode::OK, "{path}");
            let resp = send(&ctx.app, Method::HEAD, &format!("/deb/myrepo/{path}"), "").await;
            assert_eq!(resp.status(), StatusCode::OK, "HEAD {path}");
        }
        // Traversal still rejected.
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/./../other/Release", "").await;
        assert_ne!(resp.status(), StatusCode::OK);
    }

    #[tokio::test]
    async fn test_deb_reserved_names_have_no_cache() {
        let ctx = create_test_context();
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/tree.deb",
            build_test_deb("tree", "1.0"),
        )
        .await;
        for name in RESERVED
            .iter()
            .filter(|n| !n.starts_with("InRelease") && !n.ends_with(".gpg"))
        {
            let resp = send(&ctx.app, Method::GET, &format!("/deb/myrepo/{name}"), "").await;
            assert_eq!(resp.status(), StatusCode::OK, "{name}");
            assert_eq!(
                resp.headers()
                    .get("cache-control")
                    .unwrap()
                    .to_str()
                    .unwrap(),
                "no-cache",
                "{name}"
            );
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod signing_tests {
    use super::integration_tests::build_test_deb_with;
    use crate::test_helpers::{
        body_bytes, create_test_context, create_test_context_with_config, send,
    };
    use axum::http::{Method, StatusCode};
    use pgp::composed::{
        CleartextSignedMessage, Deserializable, DetachedSignature, SignedPublicKey,
    };

    /// InRelease (clearsigned) and Release.gpg (detached) must verify against
    /// the served public key, and InRelease must embed the Release text (#128).
    #[tokio::test]
    async fn test_deb_release_signatures_verify() {
        let ctx = create_test_context();
        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/pool/sig.deb",
            build_test_deb_with("sig", "1.0", "gz"),
        )
        .await;

        let release =
            body_bytes(send(&ctx.app, Method::GET, "/deb/myrepo/Release", "").await).await;
        let key = body_bytes(send(&ctx.app, Method::GET, "/deb/myrepo/pubkey.gpg", "").await).await;
        let (public, _) =
            SignedPublicKey::from_armor_single(std::io::Cursor::new(&key[..])).unwrap();

        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/InRelease", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        let inrelease = body_bytes(resp).await;
        let (msg, _) =
            CleartextSignedMessage::from_armor(std::io::Cursor::new(&inrelease[..])).unwrap();
        msg.verify(&public).unwrap();
        assert!(
            msg.signed_text().contains("SHA256:"),
            "InRelease must embed the Release body"
        );

        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/Release.gpg", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
        let gpg = body_bytes(resp).await;
        let (sig, _) =
            DetachedSignature::from_armor_single(std::io::Cursor::new(&gpg[..])).unwrap();
        sig.verify(&public, &release[..]).unwrap();

        // apt fetches these via the flat-repo dot path too.
        let resp = send(&ctx.app, Method::GET, "/deb/myrepo/./InRelease", "").await;
        assert_eq!(resp.status(), StatusCode::OK);
    }

    /// Unsigned mode: no signature endpoints, and stale InRelease/Release.gpg
    /// from a previously-signed deployment are removed on regeneration.
    #[tokio::test]
    async fn test_deb_unsigned_mode_removes_stale_signatures() {
        let ctx = create_test_context_with_config(|c| c.signing.enabled = false);
        for name in ["InRelease", "Release.gpg"] {
            ctx.state
                .storage
                .put(&format!("deb/myrepo/{name}"), b"stale")
                .await
                .unwrap();
        }

        send(
            &ctx.app,
            Method::PUT,
            "/deb/myrepo/pool/sig.deb",
            build_test_deb_with("sig", "1.0", "gz"),
        )
        .await;

        for name in ["InRelease", "Release.gpg", "pubkey.gpg"] {
            let resp = send(&ctx.app, Method::GET, &format!("/deb/myrepo/{name}"), "").await;
            assert_eq!(resp.status(), StatusCode::NOT_FOUND, "{name}");
        }
    }
}
